Change Stage superset deployment to use internal-data-hub repo
AICoE/aicoe-cd pull request #302
Opened 2021-08-04 20:01 UTC by rimolive

## This Pull Request implements
Change superset deployment to use internal-data-hub repo

## If migrating an Application to ArgoCD
- [X] I have completed the list of action items on [this page](https://aicoe.github.io/aicoe-cd/get_argocd_to_manage_your_app/)

2021-08-04 20:02 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **rimolive** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Faicoe-cd).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/aicoe-cd/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["rimolive"]} -->

2021-08-04 20:05 UTC, anishasthana reviewed
/lgtm

2021-08-05 16:00 UTC, maulikjs approved these changes

2021-08-05 16:01 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/aicoe-cd/pull/302#pullrequestreview-723536536" title="Approved">maulikjs</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Faicoe-cd).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/aicoe-cd/blob/main/OWNERS)~~ [maulikjs]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-05 16:02 UTC, maulikjs requested changes

2021-08-05 16:02 UTC, maulikjs commented on manifests/overlays/prod/applications/data_hub/dh-stage-superset.yaml
> +    path: kfdefs/overlays/prod/dh-stage-trino
shouldnt this be `change/dh-stage-trino` ?

2021-08-05 16:02 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **anishasthana** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Faicoe-cd).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/aicoe-cd/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["anishasthana"]} -->

2021-08-05 16:02 UTC, merged